#!/bin/bash

#SBATCH --job-name=samplesxtoy
#SBATCH --account=r00302
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --mem=128G
#SBATCH --time=24:00:00
#SBATCH --array=1-10
#SBATCH --mail_type=FAIL
#SBATCH --mail-user=justren@iu.edu
#SBATCH --output=logs/modkit_%A_%a.out
#SBATCH --error=logs/modkit_%A_%a.err

set -e
set -o pipefail

# 1. Load environment logic
source /N/slate/justren/6mA_modkit/slurm_setup/config.sh
source /N/slate/justren/6mA_modkit/slurm_setup/slurm_utils.sh

# 2. Get info for the array task
ROW_INFO=$(get_sample_info "$MANIFEST" "$SLURM_ARRAY_TASK_ID")

# 3. Parse variables
IFS=$'\t' read -r SAMPLE_ID DONOR CONDITION RAW_PATH OUT_DIR BED_NAME <<< "$ROW_INFO"

# Define final output path
EXPECTED_BED="${OUT_DIR}/${BED_NAME}"

echo "Processing $SAMPLE_ID ($CONDITION)"
echo "Source: $RAW_PATH"
echo "Dest:   $EXPECTED_BED"

# 4. Create output directory if it doesn't exist
mkdir -p "$OUT_DIR"
